Fix compile breaking bug in assembler
The commit "Changing assembler to make cosmetic change after DSS bugfix
keeping spaces if present." (3eeda10cf23469f4b669437290895acfecd290b7)
introduced the following build failures:

12>------ Build started: Project: DirectX11, Configuration: Zip Release x64 ------
12>  Assembler.cpp
12>..\D3D_Shaders\Assembler.cpp(146): error C2446: '==' : no conversion from 'const char *' to 'int'
12>          There is no context in which this conversion is possible
12>..\D3D_Shaders\Assembler.cpp(146): error C2040: '==' : 'int' differs in levels of indirection from 'const char [2]'
12>..\D3D_Shaders\Assembler.cpp(160): error C2446: '==' : no conversion from 'const char *' to 'int'
12>          There is no context in which this conversion is possible
12>..\D3D_Shaders\Assembler.cpp(160): error C2040: '==' : 'int' differs in levels of indirection from 'const char [2]'
12>..\D3D_Shaders\Assembler.cpp(174): error C2446: '==' : no conversion from 'const char *' to 'int'
12>          There is no context in which this conversion is possible
12>..\D3D_Shaders\Assembler.cpp(174): error C2040: '==' : 'int' differs in levels of indirection from 'const char [2]'
12>..\D3D_Shaders\Assembler.cpp(213): error C2446: '==' : no conversion from 'const char *' to 'int'
12>          There is no context in which this conversion is possible
12>..\D3D_Shaders\Assembler.cpp(213): error C2040: '==' : 'int' differs in levels of indirection from 'const char [2]'
12>..\D3D_Shaders\Assembler.cpp(226): error C2446: '==' : no conversion from 'const char *' to 'int'
12>          There is no context in which this conversion is possible
12>..\D3D_Shaders\Assembler.cpp(226): error C2040: '==' : 'int' differs in levels of indirection from 'const char [2]'
12>..\D3D_Shaders\Assembler.cpp(239): error C2446: '==' : no conversion from 'const char *' to 'int'
12>          There is no context in which this conversion is possible
12>..\D3D_Shaders\Assembler.cpp(239): error C2040: '==' : 'int' differs in levels of indirection from 'const char [2]'

The [] operator on a string returns a char which cannot be compared
against a string with the == operator. This commit changes the string
being compared against to a char which can use the == operator.

This issue was introduced in a cleanup patch for #37