Workaround VS2013 toolchain bug
This cryptic error message showed up when building with the VS2013
toolchain (using VS2015 IDE):

13>HackerContext.cpp(512): error C3867: 'HackerContext::SetShader': function call missing argument list; use '&HackerContext::SetShader' to create a pointer to member
13>          HackerContext.cpp(533) : see reference to function template instantiation 'void HackerContext::DeferredShaderReplacement<ID3D11VertexShader,void ID3D11DeviceContext::`vcall'{608}'(ID3D11VertexShader **,ID3D11ClassInstance **,UINT *),void ID3D11DeviceContext::`vcall'{88}'(ID3D11VertexShader *,ID3D11ClassInstance *const *,UINT),HRESULT ID3D11Device::`vcall'{96}'(const void *,SIZE_T,ID3D11ClassLinkage *,ID3D11VertexShader **)>(ID3D11DeviceChild *,UINT64,wchar_t *)' being compiled
13>HackerContext.cpp(512): error C2568: '->*' : unable to resolve function overload
13>          c:\cygwin\home\dss\3dmigoto\directx11\HackerContext.h(193): could be 'void HackerContext::SetShader(ID3D11Shader *,ID3D11ClassInstance *const *,UINT,std::unordered_map<ID3D11Shader*,UINT64,std::hash<_Ty*>,std::equal_to<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>> *,std::unordered_map<ID3D11Shader*,ID3D11Shader*,std::hash<_Ty*>,std::equal_to<_Kty>,std::allocator<std::pair<const _Kty,ID3D11Shader>>> *,std::unordered_map<ID3D11Shader*,ID3D11Shader*,std::hash<_Ty*>,std::equal_to<_Kty>,std::allocator<std::pair<const _Kty,ID3D11Shader>>> *,std::set<UINT64,std::less<_Ty>,std::allocator<_Ty>> *,UINT64,UINT64 *,ID3D11Shader **)'
13>          with
13>          [
13>              _Kty=ID3D11Shader *
13>  ,            _Ty=UINT64
13>          ]

This is a toolchain bug that is mistaking which object the member
function pointer applies to - it tries to map it to the template
HackerContext::SetShader function, even though we passed it
the very real and not at all templated function
&ID3D11DeviceContext::VSSetShader.

It does not show up when built with the VS2015 toolchain.

Giving the member function pointer a unique name works around the
issue.